apiVersion: skaffold/v4beta2
kind: Config
build:
  artifacts:
    - image: tons/whoami-go
  tagPolicy:
    inputDigest: { }
deploy:
  helm:
    releases:
      - name: whoami-go
        namespace: whoami
        createNamespace: true
        chartPath: helm
        setValueTemplates:
          repository:
            image: tons/whoami-go
          serviceAccount:
            annotations:
              "eks.amazonaws.com/role-arn": "arn:aws:iam::767224633206:role/instance-cluster-test-im-manager-tons"
